$ErrorActionPreference = "Stop"
$root = Resolve-Path (Join-Path $PSScriptRoot "..")
Set-Location $root
$publicKeyPem = [string]$env:PANGHU_COMMERCIAL_MANIFEST_PUBLIC_KEY_PEM
if ($env:PANGHU_REQUIRE_COMMERCIAL_MANIFEST_PUBLIC_KEY -eq "1" -and [string]::IsNullOrWhiteSpace($publicKeyPem)) {
    throw "Production commercial build requires PANGHU_COMMERCIAL_MANIFEST_PUBLIC_KEY_PEM."
}
if (-not (Test-Path -LiteralPath ".venv")) {
    python -m venv .venv
}
$python = Join-Path $root ".venv\Scripts\python.exe"
$assets = Join-Path $root "assets"
$icon = Join-Path $assets "panghu-avatar.ico"
$appName = [string]::Concat([char]0x80D6, [char]0x864E, "AI", [char]0x5BA2, [char]0x6237, [char]0x7AEF)
& $python -m pip install --upgrade pip
& $python -m pip install -r requirements-build.txt
$publicKeyModule = Join-Path $root "src\commercial_manifest_public_key.py"
$publicKeyJson = ConvertTo-Json -Compress $publicKeyPem
$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllLines($publicKeyModule, @(
    "# Generated by build script. Do not commit.",
    "PUBLIC_KEY_PEM = $publicKeyJson"
), $utf8NoBom)
if (-not (Test-Path -LiteralPath $publicKeyModule)) {
    throw "Failed to generate commercial manifest public key module."
}
$certifiData = & $python -c "import certifi, pathlib; print(pathlib.Path(certifi.where()).parent)"
$pyinstallerArgs = @(
    "-m", "PyInstaller",
    "--noconfirm",
    "--clean",
    "--windowed",
    "--name", $appName,
    "--icon", $icon,
    "--add-data", "$certifiData;certifi",
    "--add-data", "$($assets);assets",
    "--distpath", "release",
    "--workpath", "build",
    "--specpath", "build",
    "src\panghu_codex_installer.py"
)
& $python @pyinstallerArgs
$releaseDir = Join-Path (Join-Path $root "release") $appName
$zip = Join-Path (Join-Path $root "release") "$($appName)-Windows.zip"
$tempZip = Join-Path (Join-Path $root "release") "$($appName)-Windows.zip.tmp"
if (Test-Path -LiteralPath $tempZip) {
    Remove-Item -LiteralPath $tempZip -Force
}
Add-Type -AssemblyName System.IO.Compression.FileSystem
[System.IO.Compression.ZipFile]::CreateFromDirectory($releaseDir, $tempZip)
$zipArchive = $null
try {
    $zipArchive = [System.IO.Compression.ZipFile]::OpenRead($tempZip)
    $exeEntryName = "$appName.exe"
    $hasExe = $zipArchive.Entries | Where-Object { $_.FullName -eq $exeEntryName } | Select-Object -First 1
    if (-not $hasExe) {
        throw "Windows zip validation failed: missing $exeEntryName."
    }
    if ($zipArchive.Entries.Count -lt 2) {
        throw "Windows zip validation failed: package has too few files."
    }
}
finally {
    if ($zipArchive -ne $null) {
        $zipArchive.Dispose()
    }
}
Move-Item -LiteralPath $tempZip -Destination $zip -Force
Write-Host "Build finished."
Write-Host (Join-Path $releaseDir "$appName.exe")
Write-Host $zip
